export enum ERoutes {
  ABOUT = 'about',
  APPS = 'apps',
  APPS_ANDROID = 'android',
  ARTICLES = 'articles',
  COOKIE_POLICY = 'cookie-policy',
  DATA = 'data',
  HELP = 'help',
  MAP = 'map',
  METHODOLOGY = 'methodology',
  MUNICIPALITY = 'municipality/:name',
  OPEN_DATA = 'open-data',
  PRIVACY_POLICY = 'privacy-policy',
  SOLUTIONS = 'solutions',
  SOLUTIONS_OVERVIEW = 'overview',
  STATISTICS = 'statistics',
  TERMS_OF_SERVICE = 'terms-of-use',
  TEST = 'internet-speed-test',
  TEST_PROGRESS = 'progress',
  TEST_HISTORY = 'history',
  TEST_HYSTORY_RESULTS = 'results/:id',
  PAGE_NOT_FOUND = 'page-not-found',
  WIZARD = 'wizard',
  CONTACT = 'contact',
}
